name: 🚀 Щоденний пост у канал

on:
  schedule:
    - cron: '0 12 * * *'  # Запускається щодня о 12:00 UTC
  workflow_dispatch:

jobs:
  send_post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install python-telegram-bot

      - name: Run send_channel_post.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          # Наприклад: @RelaxBoxUA
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python send_channel_post.py
